<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DoctorSeeder extends Seeder
{
    public function run()
    {
        $doctores = [
            [
                'codigo' => '00031',
                'primer_nombre' => 'Carlos',
                'segundo_nombre' => 'Alberto',
                'primer_apellido' => 'González',
                'segundo_apellido' => 'Mendoza',
                'cedula' => '0012301990123A',
                'telefono' => '87543210',
                'email' => 'carlos.gonzalez@example.com',
                'especialidad_id' => 21,
                'departamento_id' => 1,
                'fecha_contratacion' => '2023-01-15',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/carlos_gonzalez.jpg',
                'fecha_nacimiento' => '1970-05-10',
                'sexo' => 'M',
                'usuario_id' => 31,
            ],
            [
                'codigo' => '00002',
                'primer_nombre' => 'María',
                'segundo_nombre' => 'Josefina',
                'primer_apellido' => 'Lopez',
                'segundo_apellido' => 'Ramirez',
                'cedula' => '0023402981123B',
                'telefono' => '86543210',
                'email' => 'maria.lopez@example.com',
                'especialidad_id' => 2,
                'departamento_id' => 21,
                'fecha_contratacion' => '2023-02-12',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/maria_lopez.jpg',
                'fecha_nacimiento' => '1980-07-22',
                'sexo' => 'F',
                'usuario_id' => 2,
            ],
            [
                'codigo' => '00003',
                'primer_nombre' => 'Juan',
                'segundo_nombre' => 'Carlos',
                'primer_apellido' => 'Martinez',
                'segundo_apellido' => 'Castillo',
                'cedula' => '0034503881234C',
                'telefono' => '89543210',
                'email' => 'juan.martinez@example.com',
                'especialidad_id' => 3,
                'departamento_id' => 13,
                'fecha_contratacion' => '2023-03-20',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/juan_martinez.jpg',
                'fecha_nacimiento' => '1990-01-15',
                'sexo' => 'M',
                'usuario_id' => 3,
            ],
            [
                'codigo' => '00004',
                'primer_nombre' => 'Ana',
                'segundo_nombre' => 'Lucía',
                'primer_apellido' => 'Hernández',
                'segundo_apellido' => 'Ortiz',
                'cedula' => '0045604782345D',
                'telefono' => '83543210',
                'email' => 'ana.hernandez@example.com',
                'especialidad_id' => 1,
                'departamento_id' => 10,
                'fecha_contratacion' => '2023-04-15',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/ana_hernandez.jpg',
                'fecha_nacimiento' => '1985-10-05',
                'sexo' => 'F',
                'usuario_id' => 4,
            ],
            [
                'codigo' => '00005',
                'primer_nombre' => 'Pedro',
                'segundo_nombre' => 'Antonio',
                'primer_apellido' => 'Morales',
                'segundo_apellido' => 'Gutiérrez',
                'cedula' => '0056705683456E',
                'telefono' => '84543210',
                'email' => 'pedro.morales@example.com',
                'especialidad_id' => 7,
                'departamento_id' => 22,
                'fecha_contratacion' => '2023-05-12',
                'estado' => 'inactivo',
                'horario_trabajo' => '8 PM - 5 AM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/pedro_morales.jpg',
                'fecha_nacimiento' => '1975-09-20',
                'sexo' => 'M',
                'usuario_id' => 5,
            ],
            [
                'codigo' => '00006',
                'primer_nombre' => 'Sofía',
                'segundo_nombre' => 'Isabel',
                'primer_apellido' => 'Vargas',
                'segundo_apellido' => 'Jiménez',
                'cedula' => '0067806784567F',
                'telefono' => '87561234',
                'email' => 'sofia.vargas@example.com',
                'especialidad_id' => 8,
                'departamento_id' => 14,
                'fecha_contratacion' => '2023-06-01',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/sofia_vargas.jpg',
                'fecha_nacimiento' => '1995-03-12',
                'sexo' => 'F',
                'usuario_id' => 6,
            ],
            [
                'codigo' => '00007',
                'primer_nombre' => 'Luis',
                'segundo_nombre' => 'Fernando',
                'primer_apellido' => 'Rivas',
                'segundo_apellido' => 'Ruiz',
                'cedula' => '0078907895678G',
                'telefono' => '89561234',
                'email' => 'luis.rivas@example.com',
                'especialidad_id' => 8,
                'departamento_id' => 14,
                'fecha_contratacion' => '2023-07-25',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/luis_rivas.jpg',
                'fecha_nacimiento' => '1980-08-18',
                'sexo' => 'M',
                'usuario_id' => 7,
            ],
            [
                'codigo' => '00008',
                'primer_nombre' => 'Gloria',
                'segundo_nombre' => 'Esperanza',
                'primer_apellido' => 'Rivera',
                'segundo_apellido' => 'Sánchez',
                'cedula' => '0089018906789H',
                'telefono' => '86561234',
                'email' => 'gloria.rivera@example.com',
                'especialidad_id' => 25,
                'departamento_id' => 1,
                'fecha_contratacion' => '2023-08-30',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/gloria_rivera.jpg',
                'fecha_nacimiento' => '1992-11-25',
                'sexo' => 'F',
                'usuario_id' => 8,
            ],
            [
                'codigo' => '00009',
                'primer_nombre' => 'José',
                'segundo_nombre' => 'Manuel',
                'primer_apellido' => 'Rodríguez',
                'segundo_apellido' => 'Hernández',
                'cedula' => '0090129017890I',
                'telefono' => '87567890',
                'email' => 'jose.rodriguez@example.com',
               'especialidad_id' => 8,
                'departamento_id' => 14,
                'fecha_contratacion' => '2023-09-05',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/jose_rodriguez.jpg',
                'fecha_nacimiento' => '1987-02-14',
                'sexo' => 'M',
                'usuario_id' => 9,
            ],
            [
                'codigo' => '00010',
                'primer_nombre' => 'Elena',
                'segundo_nombre' => 'Victoria',
                'primer_apellido' => 'Santos',
                'segundo_apellido' => 'López',
                'cedula' => '0101230128901J',
                'telefono' => '89567890',
                'email' => 'elena.santos@example.com',
                'especialidad_id' => 9,
                'departamento_id' => 15,
                'fecha_contratacion' => '2023-10-01',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/elena_santos.jpg',
                'fecha_nacimiento' => '1990-06-30',
                'sexo' => 'F',
                'usuario_id' => 10,
            ],
            [
                'codigo' => '00011',
                'primer_nombre' => 'Daniel',
                'segundo_nombre' => 'Alejandro',
                'primer_apellido' => 'Torres',
                'segundo_apellido' => 'Díaz',
                'cedula' => '0112341239012K',
                'telefono' => '87568901',
                'email' => 'daniel.torres@example.com',
                'especialidad_id' => 9,
                'departamento_id' => 15,
                'fecha_contratacion' => '2023-11-15',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/daniel_torres.jpg',
                'fecha_nacimiento' => '1978-12-24',
                'sexo' => 'M',
                'usuario_id' => 11,
            ],
            [
                'codigo' => '00012',
                'primer_nombre' => 'Adriana',
                'segundo_nombre' => 'Beatriz',
                'primer_apellido' => 'Ramírez',
                'segundo_apellido' => 'Mendoza',
                'cedula' => '0123452340123L',
                'telefono' => '89568901',
                'email' => 'adriana.ramirez@example.com',
                'especialidad_id' => 11,
                'departamento_id' => 8,
                'fecha_contratacion' => '2023-12-20',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/adriana_ramirez.jpg',
                'fecha_nacimiento' => '1985-03-15',
                'sexo' => 'F',
                'usuario_id' => 12,
            ],
            [
                'codigo' => '00013',
                'primer_nombre' => 'Francisco',
                'segundo_nombre' => 'Javier',
                'primer_apellido' => 'Pérez',
                'segundo_apellido' => 'Rojas',
                'cedula' => '0134563451234M',
                'telefono' => '86568901',
                'email' => 'francisco.perez@example.com',
                'especialidad_id' => 11,
                'departamento_id' => 8,
                'fecha_contratacion' => '2023-11-22',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/francisco_perez.jpg',
                'fecha_nacimiento' => '1993-04-23',
                'sexo' => 'M',
                'usuario_id' => 13,
            ],
            [
                'codigo' => '00014',
                'primer_nombre' => 'Gabriela',
                'segundo_nombre' => 'Lucía',
                'primer_apellido' => 'Ortega',
                'segundo_apellido' => 'Castro',
                'cedula' => '0145674562345N',
                'telefono' => '87568901',
                'email' => 'gabriela.ortega@example.com',
                'especialidad_id' => 11,
                'departamento_id' => 8,
                'fecha_contratacion' => '2023-10-05',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/gabriela_ortega.jpg',
                'fecha_nacimiento' => '1998-02-05',
                'sexo' => 'F',
                'usuario_id' => 14,
            ],
            [
                'codigo' => '00015',
                'primer_nombre' => 'Fernando',
                'segundo_nombre' => 'José',
                'primer_apellido' => 'Ruiz',
                'segundo_apellido' => 'Serrano',
                'cedula' => '0156785673456O',
                'telefono' => '83568901',
                'email' => 'fernando.ruiz@example.com',
                'especialidad_id' => 11,
                'departamento_id' => 8,
                'fecha_contratacion' => '2023-08-18',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/fernando_ruiz.jpg',
                'fecha_nacimiento' => '1973-06-11',
                'sexo' => 'M',
                'usuario_id' => 15,
            ],
            [
                'codigo' => '00016',
                'primer_nombre' => 'Margarita',
                'segundo_nombre' => 'Teresa',
                'primer_apellido' => 'Vargas',
                'segundo_apellido' => 'Romero',
                'cedula' => '0167896784567P',
                'telefono' => '87567890',
                'email' => 'margarita.vargas@example.com',
                'especialidad_id' => 12,
                'departamento_id' => 11,
                'fecha_contratacion' => '2023-07-30',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/margarita_vargas.jpg',
                'fecha_nacimiento' => '1983-11-01',
                'sexo' => 'F',
                'usuario_id' => 16,
            ],
            [
                'codigo' => '00017',
                'primer_nombre' => 'Ricardo',
                'segundo_nombre' => 'Andrés',
                'primer_apellido' => 'Jiménez',
                'segundo_apellido' => 'Martínez',
                'cedula' => '0178907895678Q',
                'telefono' => '89567890',
                'email' => 'ricardo.jimenez@example.com',
                'especialidad_id' => 15,
                'departamento_id' => 7,
                'fecha_contratacion' => '2023-06-20',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/ricardo_jimenez.jpg',
                'fecha_nacimiento' => '1999-12-12',
                'sexo' => 'M',
                'usuario_id' => 17,
            ],
            [
                'codigo' => '00018',
                'primer_nombre' => 'Liliana',
                'segundo_nombre' => 'Patricia',
                'primer_apellido' => 'Molina',
                'segundo_apellido' => 'López',
                'cedula' => '0189018906789R',
                'telefono' => '87568901',
                'email' => 'liliana.molina@example.com',
                'especialidad_id' => 15,
                'departamento_id' => 7,
                'fecha_contratacion' => '2023-05-15',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/liliana_molina.jpg',
                'fecha_nacimiento' => '1989-07-19',
                'sexo' => 'F',
                'usuario_id' => 18,
            ],
            [
                'codigo' => '00019',
                'primer_nombre' => 'Mauricio',
                'segundo_nombre' => 'David',
                'primer_apellido' => 'Castro',
                'segundo_apellido' => 'García',
                'cedula' => '0190129017890S',
                'telefono' => '89568901',
                'email' => 'mauricio.castro@example.com',
                'especialidad_id' => 17,
                'departamento_id' => 3,
                'fecha_contratacion' => '2023-04-20',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/mauricio_castro.jpg',
                'fecha_nacimiento' => '1984-10-30',
                'sexo' => 'M',
                'usuario_id' => 19,
            ],
            [
                'codigo' => '00020',
                'primer_nombre' => 'Valeria',
                'segundo_nombre' => 'Isabel',
                'primer_apellido' => 'Mejía',
                'segundo_apellido' => 'Espinoza',
                'cedula' => '0201230128901T',
                'telefono' => '83568901',
                'email' => 'valeria.mejia@example.com',
                'especialidad_id' => 17,
                'departamento_id' => 3,
                'fecha_contratacion' => '2023-03-30',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/valeria_mejia.jpg',
                'fecha_nacimiento' => '1992-09-05',
                'sexo' => 'F',
                'usuario_id' => 20,
            ],
            [
                'codigo' => '00021',
                'primer_nombre' => 'Carlos',
                'segundo_nombre' => 'Miguel',
                'primer_apellido' => 'Lara',
                'segundo_apellido' => 'Córdoba',
                'cedula' => '0212341239012U',
                'telefono' => '87568901',
                'email' => 'carlos.lara@example.com',
                'especialidad_id' => 18,
                'departamento_id' => 17,
                'fecha_contratacion' => '2023-02-14',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/carlos_lara.jpg',
                'fecha_nacimiento' => '1981-01-23',
                'sexo' => 'M',
                'usuario_id' => 21,
            ],
            [
                'codigo' => '00022',
                'primer_nombre' => 'Alicia',
                'segundo_nombre' => 'Margarita',
                'primer_apellido' => 'Ríos',
                'segundo_apellido' => 'Peña',
                'cedula' => '0223452340123V',
                'telefono' => '89567890',
                'email' => 'alicia.rios@example.com',
                'especialidad_id' => 20,
                'departamento_id' => 18,
                'fecha_contratacion' => '2023-01-09',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/alicia_rios.jpg',
                'fecha_nacimiento' => '1995-05-28',
                'sexo' => 'F',
                'usuario_id' => 22,
            ],
            [
                'codigo' => '00023',
                'primer_nombre' => 'David',
                'segundo_nombre' => 'Enrique',
                'primer_apellido' => 'Cruz',
                'segundo_apellido' => 'Guzmán',
                'cedula' => '0234563451234W',
                'telefono' => '83567890',
                'email' => 'david.cruz@example.com',
                'especialidad_id' => 20,
                'departamento_id' => 18,
                'fecha_contratacion' => '2023-12-12',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/david_cruz.jpg',
                'fecha_nacimiento' => '1974-07-07',
                'sexo' => 'M',
                'usuario_id' => 23,
            ],
            [
                'codigo' => '00024',
                'primer_nombre' => 'Sofía',
                'segundo_nombre' => 'Andrea',
                'primer_apellido' => 'González',
                'segundo_apellido' => 'Velásquez',
                'cedula' => '0245674562345X',
                'telefono' => '87568901',
                'email' => 'sofia.gonzalez@example.com',
                'especialidad_id' => 20,
                'departamento_id' => 18,
                'fecha_contratacion' => '2023-11-10',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/sofia_gonzalez.jpg',
                'fecha_nacimiento' => '1988-11-29',
                'sexo' => 'F',
                'usuario_id' => 24,
            ],
            [
                'codigo' => '00025',
                'primer_nombre' => 'Javier',
                'segundo_nombre' => 'Esteban',
                'primer_apellido' => 'Vargas',
                'segundo_apellido' => 'Salazar',
                'cedula' => '0256785673456Y',
                'telefono' => '83568901',
                'email' => 'javier.vargas@example.com',
                'especialidad_id' => 21,
                'departamento_id' => 1,
                'fecha_contratacion' => '2023-10-25',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/javier_vargas.jpg',
                'fecha_nacimiento' => '1977-04-14',
                'sexo' => 'M',
                'usuario_id' => 25,
            ],
            [
                'codigo' => '00026',
                'primer_nombre' => 'Elena',
                'segundo_nombre' => 'María',
                'primer_apellido' => 'Ortega',
                'segundo_apellido' => 'Romero',
                'cedula' => '0267896784567Z',
                'telefono' => '89567890',
                'email' => 'elena.ortega@example.com',
                'especialidad_id' => 21,
                'departamento_id' => 1,
                'fecha_contratacion' => '2023-09-18',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/elena_ortega.jpg',
                'fecha_nacimiento' => '1982-08-22',
                'sexo' => 'F',
                'usuario_id' => 26,
            ],
            [
                'codigo' => '00027',
                'primer_nombre' => 'Luis',
                'segundo_nombre' => 'Eduardo',
                'primer_apellido' => 'Díaz',
                'segundo_apellido' => 'Serrano',
                'cedula' => '0278907895678A',
                'telefono' => '87568901',
                'email' => 'luis.diaz@example.com',
                'especialidad_id' => 23,
                'departamento_id' => 6,
                'fecha_contratacion' => '2023-08-01',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/luis_diaz.jpg',
                'fecha_nacimiento' => '1986-03-11',
                'sexo' => 'M',
                'usuario_id' => 27,
            ],
            [
                'codigo' => '00028',
                'primer_nombre' => 'Marta',
                'segundo_nombre' => 'Elena',
                'primer_apellido' => 'Torres',
                'segundo_apellido' => 'García',
                'cedula' => '0289018906789B',
                'telefono' => '83567890',
                'email' => 'marta.torres@example.com',
                'especialidad_id' => 23,
                'departamento_id' => 6,
                'fecha_contratacion' => '2023-07-15',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/marta_torres.jpg',
                'fecha_nacimiento' => '1979-12-30',
                'sexo' => 'F',
                'usuario_id' => 28,
            ],
            [
                'codigo' => '00029',
                'primer_nombre' => 'Rosa',
                'segundo_nombre' => 'Isabel',
                'primer_apellido' => 'Gómez',
                'segundo_apellido' => 'Rodríguez',
                'cedula' => '0290129017890C',
                'telefono' => '87568901',
                'email' => 'rosa.gomez@example.com',
                'especialidad_id' => 8,
                'departamento_id' => 14,
                'fecha_contratacion' => '2023-06-10',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'León, Nicaragua',
                'foto' => 'public/images/rosa_gomez.jpg',
                'fecha_nacimiento' => '1993-10-18',
                'sexo' => 'F',
                'usuario_id' => 29,
            ],
            [
                'codigo' => '00030',
                'primer_nombre' => 'Fernando',
                'segundo_nombre' => 'José',
                'primer_apellido' => 'Reyes',
                'segundo_apellido' => 'Alvarado',
                'cedula' => '0301230128901D',
                'telefono' => '83568901',
                'email' => 'fernando.reyes@example.com',
                'especialidad_id' => 24,
                'departamento_id' => 5,
                'fecha_contratacion' => '2023-05-05',
                'estado' => 'activo',
                'horario_trabajo' => '8 AM - 5 PM',
                'direccion' => 'Chinandega, Nicaragua',
                'foto' => 'public/images/fernando_reyes.jpg',
                'fecha_nacimiento' => '1984-06-25',
                'sexo' => 'M',
                'usuario_id' => 30,
            ],
        ];
        

        DB::table('doctores')->insert($doctores);
    }
}
